{
 "title": "Nginx Detailed",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(nginx_http_requests_total, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Nginx Historial Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic : Requests / Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[5m]))",
     "legendFormat": "Today"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total[5m] offset 1d))",
     "legendFormat": "Yesterday"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total[5m] offset 1w))",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "Success %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!~\"4..|5..\"}[5m] ))  / sum(increase(nginx_http_requests_total[5m] ))) * 100",
     "legendFormat": "Today"
    },
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!~\"4..|5..\"}[5m] offset 1d))  / sum(increase(nginx_http_requests_total[5m] offset 1d))) * 100",
     "legendFormat": "Yesteday"
    },
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!~\"4..|5..\"}[5m] offset 1w))  / sum(increase(nginx_http_requests_total[5m] offset 1w))) * 100",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{ status!~\"2..|3..\"}[5m]))  / sum(increase(nginx_http_requests_total[5m]))) * 100",
     "legendFormat": "Today"
    },
    {
     "expr": "(sum(increase(nginx_http_requests_total{ status!~\"2..|3..\"}[5m] offset 1d))  / sum(increase(nginx_http_requests_total[5m] offset 1d))) * 100",
     "legendFormat": "Yesterday"
    },
    {
     "expr": "(sum(increase(nginx_http_requests_total{ status!~\"2..|3..\"}[5m] offset 1w))  / sum(increase(nginx_http_requests_total[5m] offset 1w))) * 100",
     "legendFormat": "Last Week"
    }
   ]
  },
  { "title": "Nginx Current Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Traffic : Requests / Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{cluster=~\"$cluster\", cache_status!~\"MISS|NONE\"}[5m]))",
     "legendFormat": "Cached"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{cluster=~\"$cluster\", cache_status =~ \"MISS|NONE\"}[5m]))",
     "legendFormat": "Not Cached"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{cluster=~\"$cluster\", status=\"345\"}[5m]))",
     "legendFormat": "Blocked Request Outside India"
    }
   ]
  },
  {
   "title": "Nginx Cache Hit count ( Approx )",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(nginx_http_requests_total{sb_cluster=~\"$cluster\"}[${__range_s}s])) by (cache_status))",
     "legendFormat": "{{cache_status}}"
    }
   ]
  },
  {
   "title": "2xx Success %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", status!~\"3..|4..|5..\"}[5m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total{cluster=~\"$cluster\"}[5m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "5xx Error %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", status!~\"2..|3..|4..\"}[5m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total{cluster=~\"$cluster\"}[5m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "3xx Success %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", status!~\"2..|4..|5..\"}[5m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total{cluster=~\"$cluster\"}[5m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "4xx Error %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", status!~\"2..|3..|5..\"}[5m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total{cluster=~\"$cluster\"}[5m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Nginx Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_http_connections) by (state)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Nginx Metrics Error",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_metric_errors_total", "legendFormat": "{{ instance }}" }
   ]
  }
 ]
}